Rc/4.0.0
icgc-argo/uikit pull request #142
Opened 2024-01-17 04:04 UTC by ciaranschutte

**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

2024-01-17 04:10 UTC, justincorrigible approved these changes
LGTM 👍

2024-01-17 04:10 UTC, justincorrigible commented on package-lock.json
> +  "version": "3.0.1",
```suggestion
  "version": "4.0.0",
```

2024-01-17 04:10 UTC, justincorrigible commented on package-lock.json
> +      "version": "3.0.1",
```suggestion
      "version": "4.0.0",
```

2024-01-17 14:29 UTC, joneubank commented
Echoing Justin's suggestions... the RC branch name and version set don't match up, whats the expected value?

2024-01-17 14:30 UTC, joneubank requested changes
Before approving this, can you add a description to the PR with a list of the changes included in this release? The RC PR should list bug fixes, new features, etc. instead of our typical template.

2024-01-18 16:22 UTC, ciaranschutte commented
> Before approving this, can you add a description to the PR with a list of the changes included in this release? The RC PR should list bug fixes, new features, etc. instead of our typical template.
> 
> Seeing this list would also help determine if this should be a major/minor/patch version update.

discussed on Slack.
reason for major bump: grabbing the update would require importer to make changes to their code to keep expected functionality.

2024-01-18 16:25 UTC, justincorrigible commented
> > Before approving this, can you add a description to the PR with a list of the changes included in this release? The RC PR should list bug fixes, new features, etc. instead of our typical template.
> > Seeing this list would also help determine if this should be a major/minor/patch version update.
> 
> discussed on Slack. reason for major bump: grabbing the update would require importer to make changes to their code to keep expected functionality.

Glad to see that got resolved. Can I request what slack channel this was discussed in?
Ideally, this discussion was documented in the public, topic-focused channels, so the rest of the team are on the same page.

2024-01-18 16:44 UTC, joneubank approved these changes

2024-01-18 17:23 UTC, ciaranschutte commented
> > > Before approving this, can you add a description to the PR with a list of the changes included in this release? The RC PR should list bug fixes, new features, etc. instead of our typical template.
> > > Seeing this list would also help determine if this should be a major/minor/patch version update.
> > 
> > 
> > discussed on Slack. reason for major bump: grabbing the update would require importer to make changes to their code to keep expected functionality.
> 
> Glad to see that got resolved. Can I request what slack channel this was discussed in? Ideally, this discussion was documented in the public, topic-focused channels, so the rest of the team are on the same page. I just cannot seem to find which one of those it was.

sorry it was a PM following up on the PR. Will @ in public channel next time.
Documented the takeaway above.

2024-01-18 17:35 UTC, justincorrigible approved these changes

2024-01-18 18:10 UTC, merged